APP_NAME = "BOXING JOURNEY"
APP_YEAR = "2026"

GOAL_WEIGHT = 75.0
START_WEIGHT = 86.7
HEIGHT_M = 1.84

DEFAULT_LAST_RUN = "4 km"
DEFAULT_LAST_PACE = "5:27/km"

DEFAULT_BOXING_SESSIONS = "0 this week"
DEFAULT_BOXING_NOTE = "No session logged"

DEFAULT_GYM_SESSIONS = "0 this week"
DEFAULT_GYM_NOTE = "No session logged"